language: python

python:
  - '3.4'
  - '3.5'
  - '3.6'

install:
  - pip install flake8
  - pip install .[zstd]

script:
  - flake8 tests xtarfile
  - python setup.py test

before_deploy:
  - echo "$TRAVIS_TAG" > version.txt

deploy:
  skip_cleanup: true
  provider: pypi
  on:
    tags: true
    repo: ascoderu/xtarfile
    python: '3.6'
  user: ascoderu
  password:
    secure: HoWf5K2nzD54mRV+9hDgYjfvngUuJ+zXYTjukae8PUusLYEJDFrWGy2b4pCGhc37SO0WKA+R+8eGTwZKV+Tu/+HQe8QWPssJX7xWuj+BkuJQ3ivjnVxg+f+TElWUjLuelD5cU4nJG2kd70bFy9UOO2TThHIKpAewtz/d5QwBUQrADHaU5UPkjEVT4inZijgWgK/akh9pgE/f9vCKSSITMcqyu7dUSuXFtkip56FgEKzIZqdbpWT82kNyiBM0hMSAhA+khxl6hVKfbhzKxyckfcUQfyYtEebFlA0+xGYrrB008uO9/2Hj6KU09Rca0e3LlqDUkUTI7SzlDEeK+J6jFxIWpZNnsIqyEVbhCMSCzkz1zTBSabfwAGVjHyi1ziHuFu7wuxp+4ziFw2EdpIuMORiTkIFpYpdS5Kc/a6XLdYrSEWELjB9VkuUpTAQZULGbQ8/pStntxVAw1iFUr4Sf2V2aNyRuRG+xDk/SptnfFETaiBdDAcRqo+OGnNBVR/o4B4AAdlfcSxJtGu3IvhuZaWs7Xoex+StjLqZjx1FpgnMkG5j3RlpTkz+slBU4NBhLtI0FUNNSPsWCoCsnZ6FUW84mhL5nz3jvnZKdt5E2vXNy7B431PedQUfeDPemdtUyEQQcvBMv0KheMlgvj3zoJYp8FIZ+SvNux9bJJHCJ+Ok=
